PRODUCTION = False
DEBUG = True
SSL = False  # enables ssl_required decorator
SYSTEM_NAME = 'Rhizo Server'  # replace this
EXTENSIONS = []
SQLALCHEMY_DATABASE_URI = 'sqlite:///rhizo.db'  # format for postgres: 'postgres://[username]:[password]@[hostname]/[db]'
SQLALCHEMY_TRACK_MODIFICATIONS = False
DATABASE_CONNECT_OPTIONS = {}
THREADS_PER_PAGE = 8
CSRF_ENABLED = True
CSRF_SESSION_KEY = '[Random String Here]'
SECRET_KEY = '[Random String Here]'
SALT = '[Random String Here]'
KEY_PREFIX = 'RHIZO'  # replace this if you want to identify your keys more easily
TWILIO_ACCOUNT_SID = ''
TWILIO_AUTH_TOKEN = ''
TEXT_FROM_PHONE_NUMBER = ''
S3_ACCESS_KEY = ''
S3_SECRET_KEY = ''
S3_STORAGE_BUCKET = ''
OUTGOING_EMAIL_ADDRESS = ''  # these OUTGOING_EMAIL settings are required if you want to invite people to create accounts
OUTGOING_EMAIL_PASSWORD = ''
OUTGOING_EMAIL_SERVER = ''
EXTRA_NAV_ITEMS = ''
DOC_FILE_PREFIX = ''
